name: common_blocs
description: Blitz GUI package which contains all less specialized Blocs that can be used in many places.
publish_to: "None"

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0

  authentication:
    path: ../authentication
  subscription_repository:
    path: ../subscription_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
